hash-format = "sha256"

[[files]]
file = "config/yttr.css"
hash = "31bae3fcc12ba94e28ae6659fdf07a9c182d7a129caef53488798afb56f1a5f7"

[[files]]
file = "mods/advanced-networking.pw.toml"
hash = "05a7879786bc5537e8de0c7e9b02ba93c19d5b9bcea32f276808e1318e24e050"
metafile = true

[[files]]
file = "mods/affectionate.pw.toml"
hash = "f062cc71b8ef1c922cdd38b47673236bac80aebd4b127906d5172c9088bd0e7d"
metafile = true

[[files]]
file = "mods/aptitude.pw.toml"
hash = "655afb8690c8fb4a8d969d9a528d7a5ecfdd10f9b9d1f5896fcdb0dfddaaf584"
metafile = true

[[files]]
file = "mods/arch-ex.pw.toml"
hash = "d8ab07c1dcf51ad3f5cf25f425f938c3540e575e3353ff6c0f5d0c4b990a38ab"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "75dcdffc0d37e098ef12f1b149d68182337372e2d48653ffe0389b94b357a0de"
metafile = true

[[files]]
file = "mods/arcpocalypse.pw.toml"
hash = "4389ae3af4073dc3f0eda14e31ba3c0fc66e4889b2cc5c2e66254bd2477615ee"
metafile = true

[[files]]
file = "mods/armorstandeditor.pw.toml"
hash = "b0c3cd58565ed97f3e334db5438874ab574ea7000cea4be74490a47b8417a33f"
metafile = true

[[files]]
file = "mods/attraction.pw.toml"
hash = "d5cb59e4e7591e0c8139b90c1ed3fffb8504b229a96a4fe47c5df784dadebe16"
metafile = true

[[files]]
file = "mods/aurorasdecorations.pw.toml"
hash = "ac7d074c6f7d6f9532f7bbc927fc5d1c3d917949b4a87a184e6c9288a040a547"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "c59209e703e553f58306aa1a66dc30a58476f89ad2d40da540508dc72fe0311f"
metafile = true

[[files]]
file = "mods/beamforming.pw.toml"
hash = "87b329e61b4a25fddcd5c2b177b85b9784a3ef355eaa39c853ed6ea871113806"
metafile = true

[[files]]
file = "mods/bedventory.pw.toml"
hash = "af3282e3ceed5718a544c9745ffd9f463de6b1cd09a7ec677dfd527b6999e511"
metafile = true

[[files]]
file = "mods/bella.pw.toml"
hash = "c41fcc33b72091bbad84b3ae5f18bd6b24d8da213a21ced9637559092d49b202"
metafile = true

[[files]]
file = "mods/bettersmoke.pw.toml"
hash = "c1aaf90c7de6132e8a4b546cc2e7d738ddcb7e17567822cdf2652149d0f0b97b"
metafile = true

[[files]]
file = "mods/biome-technologies.pw.toml"
hash = "df1afd57d7555960ec87991c297bffd17434bee008ae8e774ca84d1d8aa89171"
metafile = true

[[files]]
file = "mods/blast-travel.pw.toml"
hash = "3070025cca4cf41ce0edd3b6106a74eab8760fcad7a73a71de1e18ef57a9ddb2"
metafile = true

[[files]]
file = "mods/blossomexperiencebottling.pw.toml"
hash = "86c3d9473877722b7b964af41742a2994baeb1a87d42ea3b2eae041ed036a368"
metafile = true

[[files]]
file = "mods/blossomlib.pw.toml"
hash = "3b7f0970aa5489ba1e6bda6e7c60c4e4582c58e7980aa0529044878465fc0b44"
metafile = true

[[files]]
file = "mods/boat-with-everything.pw.toml"
hash = "2cd7466c73adc2c29bb110a3b8295330df54bc5645d2896a763598d741edce7d"
metafile = true

[[files]]
file = "mods/bouncy-castle.pw.toml"
hash = "76aad3f61482f9023b443e10110e270ccb80e1fcbbe8754e72f676e119817c86"
metafile = true

[[files]]
file = "mods/celestria.pw.toml"
hash = "b3eda177d099ef511ccdd9d738d902c6c10f4037bd7dd0869ae9a3ff545a5d91"
metafile = true

[[files]]
file = "mods/chewstuff.pw.toml"
hash = "6ce5291b8fc4b0bd4cf43cab0619f41ac10a1705163119caeaffbaf011c809c6"
metafile = true

[[files]]
file = "mods/chime.pw.toml"
hash = "979d3cd0d08798db597cb306e134596f2acd3ff03bd2624cded8594de4bfb5bf"
metafile = true

[[files]]
file = "mods/cloak-of-gray-tomorrow.pw.toml"
hash = "e7080f92bf0a087265d65647bf9e08639b476222629253bd7cac4af0d182054c"
metafile = true

[[files]]
file = "mods/colossalcakes.pw.toml"
hash = "079ae0b48116f51d685bcb36c57869228a4ce84834f6bb321dcfb523239e5d23"
metafile = true

[[files]]
file = "mods/command-actions.pw.toml"
hash = "0f4065ebf6cdc217a2858b3e5d2558d921d4f9c819375a8169b26fa88dbdf6a4"
metafile = true

[[files]]
file = "mods/crafting-bench.pw.toml"
hash = "4b1c406a0e38ae34e9c63c1beafd9fea3a0d024714486c957b86e3f332b977c1"
metafile = true

[[files]]
file = "mods/drogtor.pw.toml"
hash = "0da6c09f627126988afb5a192e95147bf0911f954f07cf756550704c9ab4f540"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "4de24ddd51cba8dfddd2e66fa2c659013596289839f888a0c8f6222669e75637"
metafile = true

[[files]]
file = "mods/echoes-of-the-past.pw.toml"
hash = "63f6012c29b61b785795ee45c75d3701a592c48529b051a7f85dc966a6efcb24"
metafile = true

[[files]]
file = "mods/emerald-expansions.pw.toml"
hash = "237e340ea10313e013642a7c24f68f1a14bec499cace53b6bdc91794228a4256"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "a60267bf4464a726c93e1cac3594b8ce1fb2f4a41a24bccffdf737b05dcce0be"
metafile = true

[[files]]
file = "mods/engination.pw.toml"
hash = "26c5b406f3b79ed49198f59e519badfc3a0cfa5a9b852c7475788642d9b3e75c"
metafile = true

[[files]]
file = "mods/ethicalmeatfields.pw.toml"
hash = "26679081c894f4aa5500c3720dbdca3a72fa11b5305d8c7c0e604a7b3d990675"
metafile = true

[[files]]
file = "mods/fabrictailor.pw.toml"
hash = "b3e1f7b080b5c4a2e3de434a6873d84ba5bd357dff99268d45db4a79fb6d43b9"
metafile = true

[[files]]
file = "mods/fox-plushies.pw.toml"
hash = "2506864b4b09b94a6cdd7162512af422a12d031cf7eb6a090a8be6a0be6fb0f7"
metafile = true

[[files]]
file = "mods/goldtelepads.pw.toml"
hash = "29bda491e45162f25c49bde3160e63958f01085e433fe81c49bb2128ff3a87cb"
metafile = true

[[files]]
file = "mods/heighthaltingheels.pw.toml"
hash = "a4d5e5090908a5abcce2c4f407f341e6b22873d7227ed26b986466a3bacfbbfc"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "eefcd81493fa26fa8135cf85495cbfb52127aa43667c5a4faea27d16d7bb2191"
metafile = true

[[files]]
file = "mods/infused-immortality.pw.toml"
hash = "a27cff617de7bb6d08f5fe2a694d3e4aedfb1bf2f39209749ba19941a2ed900e"
metafile = true

[[files]]
file = "mods/ingstorm.pw.toml"
hash = "a12d26e421b1fd0dc0ec523b206b47a523c6b9b6ccc19420c83ece2af0ddcfcf"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "a348ec1aec5a10f7235d6741e08aea583e042049eded3d6eafd97a0688a891c0"
metafile = true

[[files]]
file = "mods/its-poppin.pw.toml"
hash = "52cf52e31f2097d9588a42a51f83719ca339433c05f889429e6b24fd1bf8a78f"
metafile = true

[[files]]
file = "mods/jackogolem.pw.toml"
hash = "d068d449d658439eff43fff372fac5392228cf6a0540dd0a94de0e0efb089f20"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "21c5ff2c70f953eaddf10d3ef09538d99da19c4cfe32aa251ef162b4d78c8160"
metafile = true

[[files]]
file = "mods/jar-it.pw.toml"
hash = "cba53c8cf5d07323709fcab76a2cf75725f868ce674a5cd900fa6f41d200e35c"
metafile = true

[[files]]
file = "mods/kahur.pw.toml"
hash = "0e760443a4996e394a50ae200e3758c4d404c0e93598643f92a78cf5502c34b8"
metafile = true

[[files]]
file = "mods/kettle.pw.toml"
hash = "94865ef86f229df1ce78a22498f41779fd56313c6e7c8efe678f7253c56c09db"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "998f45a9037fa4663bc5e2bea5de925bf4ce6352328fcaaa830db8466cc62416"
metafile = true

[[files]]
file = "mods/la-cucaracha.pw.toml"
hash = "05f21c8c213c9486012c89bc94fbd22f81a23ad8af0bea8413901d8357b8cbd0"
metafile = true

[[files]]
file = "mods/lanyard.pw.toml"
hash = "445c6a6a12512aef60e9c6956dc8f97329ac9282ce73e2763a0955200f557bb8"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "mods/limits-grapple.pw.toml"
hash = "02a76fdb09f007f29356f4431aa7269497a3189ec7d2fc797605cf76dee36bae"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "7cc268ba8c316a732881e631e00db7cf8db0891f24155475db0a4e88840cdfe8"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "c038a6ea641541af0aee754c41df71ccb662245863cecb43d64c202baf561291"
metafile = true

[[files]]
file = "mods/luckyducks.pw.toml"
hash = "58ab921c1b4498f5fb5d73a8420eeae621095da045c00e6f51c2a75ca581c0ff"
metafile = true

[[files]]
file = "mods/maprender.pw.toml"
hash = "780cbd198709c4253581abdf64223ef8c3ceeb6a176b596ea18e7480364cf396"
metafile = true

[[files]]
file = "mods/meowing.pw.toml"
hash = "9418168578c73fef540382b2e3c111ec0099531d00e245dbe0db7cbbb3b119ed"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "1c68b1e077a77dfa2cd5a63b9ad73b11406e4c0bb13ef72a4c337cb50f188740"
metafile = true

[[files]]
file = "mods/mineball.pw.toml"
hash = "1171b97eaac37bfa61cf0bd5d223a2071426f9143c65fc2cdd2a7ae6884c575d"
metafile = true

[[files]]
file = "mods/minecalc.pw.toml"
hash = "c9449977a6260567f13f2e0c56dc4263d9c2889a5d05325725c15822f46be099"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "24b56cdea0d96fc1b03b8cb6e6bb4b600c6fe730f7cd86e84004d100779ad5a1"
metafile = true

[[files]]
file = "mods/mods-in-a-jar.pw.toml"
hash = "7bb8f03584893249e1a23f97672f4fb5a06caaf73938aa86c40c5e213f5fc5f6"
metafile = true

[[files]]
file = "mods/modulus.pw.toml"
hash = "f0769a05aabeb77d221090f742127d6024af67057b5c7e52cf8e8aede6b1f99f"
metafile = true

[[files]]
file = "mods/moovy.pw.toml"
hash = "2c3da1dee1aae5dd67e0b75c38d8eeb95c0b2d23b1a3a45e4317e470bfd68be7"
metafile = true

[[files]]
file = "mods/mushroom-mod.pw.toml"
hash = "0ef254d9d44942f33ee3405ce0e253dd883b922e5af32943dc2656fa964d4f70"
metafile = true

[[files]]
file = "mods/packy.pw.toml"
hash = "44b89627acadfd474e87fb03e62c110d3bd915a12571ce78235be0fd3df2d6d9"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
hash = "b3a5f6bcab7382577050322f78a606f06e2011bf69a9baa179c687317368d1ae"
metafile = true

[[files]]
file = "mods/polaroid.pw.toml"
hash = "c531b07068714e4221b32a301712cc034856b9628ae214511125ab5088e7492f"
metafile = true

[[files]]
file = "mods/pressalttomeow.pw.toml"
hash = "d85441641625c3c7634aeb801297eaba457314ef951d8bf222f4966a51b01109"
metafile = true

[[files]]
file = "mods/pridestrips.pw.toml"
hash = "009459384f38af33e1b7bd341e6e77166f45cc5140719581a76fc3ecc89569ec"
metafile = true

[[files]]
file = "mods/qkl.pw.toml"
hash = "c9b5c7f923336eb60458492ee72e30471edefa0b5b897d279def756101895737"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "b3a33693d3a9a6d9715cdfa45bde46a9f0374c7d858a1658e8c28972e59862a1"
metafile = true

[[files]]
file = "mods/quiltgoslighlyfasterlol.pw.toml"
hash = "feee9284053ffd6435907d1bf3b5fdb7e9010237bb2a4b6a912d6f1389f8def7"
metafile = true

[[files]]
file = "mods/recovery-plus.pw.toml"
hash = "d6a3103ff1bf38bcf753a4170298c19d910f3039492b5b1bf3772d93e8910907"
metafile = true

[[files]]
file = "mods/redderstone.pw.toml"
hash = "3c0cf0c7d636df22f7672382fed2ffa8b7c80438928b13f53a1d0c80f8d6353c"
metafile = true

[[files]]
file = "mods/relativity.pw.toml"
hash = "d5898bac8e10030d12bed8ad0e3f95eedac92369065ca5bbea525eb4f63b118b"
metafile = true

[[files]]
file = "mods/restful-hellscape.pw.toml"
hash = "81af4a423b2b51c5bf7f5a31712653827b1854fa98cf9f846b18ea882fe1d5c8"
metafile = true

[[files]]
file = "mods/runic-railguns.pw.toml"
hash = "6447b49ba96a71f6982e4ca30b0baec38d9c7be3313a3c3533bfbd47fa54f1fe"
metafile = true

[[files]]
file = "mods/scarves.pw.toml"
hash = "1669901fdb99a9626180855901c1534b54a3475efd6b07a691a390b77580d631"
metafile = true

[[files]]
file = "mods/sharp-tone.pw.toml"
hash = "72112c2295123556b5a9b8d1ce20a06455b6fcaa82f443de6ba6285ad2f86e8a"
metafile = true

[[files]]
file = "mods/simplexp.pw.toml"
hash = "13bed28c4e374dcc8991a95197a09a52e433f45d2734bf74bc452cdeee7d4488"
metafile = true

[[files]]
file = "mods/smunnel.pw.toml"
hash = "f37a455becb0f81258725a9b89e24b5b13cc1845e0dc4d593031b7abe7f13ad3"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0d539d8bad8493d4196bf5f7bf216d692384f283849fa41a2e5a816a0147673e"
metafile = true

[[files]]
file = "mods/soul-under-sculk.pw.toml"
hash = "30349c04d7a0c33dd9763bbc2671a3ad0a41e3f5b7e4f15c1d8a611adb927915"
metafile = true

[[files]]
file = "mods/soul-vitric.pw.toml"
hash = "dcdb60c59e8619fd4cae9b91a62b4e0bc920c33e7512a76a680720fbaed1757d"
metafile = true

[[files]]
file = "mods/souper.pw.toml"
hash = "e97be39323a8308156c6104794303076f97b5e09c124ce423896355cdd8fa247"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "be68ef606c339bbb22f2b812db1e5264d9e3335befc0c348d4dc91a8a3e72e17"
metafile = true

[[files]]
file = "mods/succ.pw.toml"
hash = "74183ab677fd0c5275725dd22859f26c952c2369bbe4c0eedb5a38df6a5e8fa7"
metafile = true

[[files]]
file = "mods/switchy-inventories.pw.toml"
hash = "ea262aab85122326adca2b315ebe5d62394193f20300997b61b4426d48834484"
metafile = true

[[files]]
file = "mods/switchy.pw.toml"
hash = "278e901d5a4b5364df4afc05b61acc8b763ed05c79c84991af9a61598a53d915"
metafile = true

[[files]]
file = "mods/taterzens.pw.toml"
hash = "853f3e9b78f68e18118cdd92ff3619d2f849cefae363bb97808a45d3de896970"
metafile = true

[[files]]
file = "mods/the-printer.pw.toml"
hash = "ad9e8cd36629e2bd362bb8a75d9558ed8fde0b1710012b819ef649ad126f6a2f"
metafile = true

[[files]]
file = "mods/thematchmakers.pw.toml"
hash = "516a417817a1a0d83da1d8adc7b0ef216ae2f7e13b292c9dd5fbcd1b096238bb"
metafile = true

[[files]]
file = "mods/tree-hat.pw.toml"
hash = "ae2ce11325bd06ac85519db134001b25d35b5ad1ae6bf42051b3a4ce2a78ae11"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "842711b0a1baa2fc6bd2ef6c1953c735f68e73c6b7a13dee723851feb183349c"
metafile = true

[[files]]
file = "mods/tropics.pw.toml"
hash = "bd4c47e15a68b8110eef6aad500d279d587e5bf6d8b86288d5a3a0f7bdfea3d2"
metafile = true

[[files]]
file = "mods/untill.pw.toml"
hash = "6e0a0709ad8c8dbe15069439ac6c72698fd3a7e0327cb2dd0846076f808d9881"
metafile = true

[[files]]
file = "mods/vanity-splash-text.pw.toml"
hash = "97b237efdd455619095586dddbf65aa84b964db7781a4f40798f6042b3ad17d5"
metafile = true

[[files]]
file = "mods/villagerbefriending.pw.toml"
hash = "ccfd5db6c17df610a1c71f771a7eb54ba2c4f2003e2ccfe1d3c4e7542793dbde"
metafile = true

[[files]]
file = "mods/wenospeakumbrellarino.pw.toml"
hash = "7bb0072c0c67e2866a21ec175d5e536324a5b5ff94ac0c5f5e771c032365a5cf"
metafile = true

[[files]]
file = "mods/whipdashing.pw.toml"
hash = "c774b5349d333117a289e9f59e850247c276712783c4ec110ed1a72239e68f6e"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
hash = "cae479bc37fce778b7716e9884b54d5cdcb5796d661fb00db29fde09dc806d59"
metafile = true

[[files]]
file = "mods/yardwork.pw.toml"
hash = "2a7fef4cb6feb5170ec0faac6c554840ee988e0906c6dc3ad49c9f48b0afa96a"
metafile = true

[[files]]
file = "mods/yttr.pw.toml"
hash = "bb10872318ee269ed2a85f613a4e813211b6863ba9e2b1f3709354af8cd0c9aa"
metafile = true
