hash-format = "sha256"

[[files]]
file = "config/NoChatReports/NCR-Client.json"
hash = "11981fe269d7c1d231b65d2db484b1ee4f1077e32d6f8cccbcb2ff324d789063"

[[files]]
file = "config/fabrication/features.ini"
hash = "39d7a33c57267ffce167ade59b8888819a813c11f9906f9de06a76f099ff957c"

[[files]]
file = "config/midnightlib.json"
hash = "45421bbd126a17358dce57fda4e7bc3153f503e7c3f2909f20ebef86e0774a89"

[[files]]
file = "config/yosbr/config/emi.css"
hash = "b5f068482d639199645cde4d5657018afa7dd08c5a5f002715c2500a811ce20e"

[[files]]
file = "config/yttr.css"
hash = "bf1e03f6bfde8d1df9fce0880bf36ebf05a6957abfc038923d0b10a00c7b0e37"

[[files]]
file = "mods/advanced-networking.pw.toml"
hash = "5df66d1594e0e59754295cd6f5f1414f18ce47f18e583e474edf8c52e6db529c"
metafile = true

[[files]]
file = "mods/affectionate.pw.toml"
hash = "57c751a13a63e24201f0880a88376e3f5ae11b865863ebfc21f3333469f0cee8"
metafile = true

[[files]]
file = "mods/any1_of_us.pw.toml"
hash = "0b701db8b26ed435d0079457a50572bd3efb149345b3a0dd6490f8d8984c0113"
metafile = true

[[files]]
file = "mods/aptitude.pw.toml"
hash = "655afb8690c8fb4a8d969d9a528d7a5ecfdd10f9b9d1f5896fcdb0dfddaaf584"
metafile = true

[[files]]
file = "mods/arch-ex.pw.toml"
hash = "d8ab07c1dcf51ad3f5cf25f425f938c3540e575e3353ff6c0f5d0c4b990a38ab"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "75dcdffc0d37e098ef12f1b149d68182337372e2d48653ffe0389b94b357a0de"
metafile = true

[[files]]
file = "mods/arcpocalypse.pw.toml"
hash = "04bafeb7349cbb878ac129a04368a0076b0356f1614a5ef3c90d3cb5cd5b2d3f"
metafile = true

[[files]]
file = "mods/armorstandeditor.pw.toml"
hash = "30e7b44fcca0e5f7936f8fadcffb85457069d576553f7d55892792109c10e51d"
metafile = true

[[files]]
file = "mods/attraction.pw.toml"
hash = "d5cb59e4e7591e0c8139b90c1ed3fffb8504b229a96a4fe47c5df784dadebe16"
metafile = true

[[files]]
file = "mods/aurorasdecorations.pw.toml"
hash = "8f9e56b55c818715abdfe0ca2a72644f0f10f690bddf74eb03032a6bdc5cd7d3"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "c59209e703e553f58306aa1a66dc30a58476f89ad2d40da540508dc72fe0311f"
metafile = true

[[files]]
file = "mods/beamforming.pw.toml"
hash = "87b329e61b4a25fddcd5c2b177b85b9784a3ef355eaa39c853ed6ea871113806"
metafile = true

[[files]]
file = "mods/bedventory.pw.toml"
hash = "8238a70a81b55b1b26ba67d65b8bebfc6ade0b7e3a6f522da71af3825f5e20c1"
metafile = true

[[files]]
file = "mods/bella.pw.toml"
hash = "c41fcc33b72091bbad84b3ae5f18bd6b24d8da213a21ced9637559092d49b202"
metafile = true

[[files]]
file = "mods/bettersmoke.pw.toml"
hash = "df3de4ffab85bd91ab37c4c0476cea6e187a249cdea200a756f05976bb5ca345"
metafile = true

[[files]]
file = "mods/bigfanofit.pw.toml"
hash = "cf3e88d7a2ad7aa56ad6f1535bab798192ba3da9263090f07e941fd9709ead33"
metafile = true

[[files]]
file = "mods/biome-technologies.pw.toml"
hash = "60ede506ba4e76726cf76a70a8d2e68155195758bb5ef13d806b8a3d64c5432a"
metafile = true

[[files]]
file = "mods/blast-travel.pw.toml"
hash = "a1cd9bc3565e9124e6293d6f4b08ce11ecfe23942c21bb696e769ffbb9708d3a"
metafile = true

[[files]]
file = "mods/blossomexperiencebottling.pw.toml"
hash = "86c3d9473877722b7b964af41742a2994baeb1a87d42ea3b2eae041ed036a368"
metafile = true

[[files]]
file = "mods/blossomlib.pw.toml"
hash = "3b7f0970aa5489ba1e6bda6e7c60c4e4582c58e7980aa0529044878465fc0b44"
metafile = true

[[files]]
file = "mods/boat-with-everything.pw.toml"
hash = "057061da359d2d2c87aa85e18d6a1d633adf1ec1408380a19afe252dffea6073"
metafile = true

[[files]]
file = "mods/bouncy-castle.pw.toml"
hash = "d0446817acbad51d26396f64cf3101b513d0879c9e355e942c3ef69fe3a89c6a"
metafile = true

[[files]]
file = "mods/cake-world.pw.toml"
hash = "e7864bd6708763c2b3a040006c70caea1f9f9bf92067e5160e197c1aa0426f72"
metafile = true

[[files]]
file = "mods/celestria.pw.toml"
hash = "b3eda177d099ef511ccdd9d738d902c6c10f4037bd7dd0869ae9a3ff545a5d91"
metafile = true

[[files]]
file = "mods/chewstuff.pw.toml"
hash = "6ce5291b8fc4b0bd4cf43cab0619f41ac10a1705163119caeaffbaf011c809c6"
metafile = true

[[files]]
file = "mods/chime.pw.toml"
hash = "979d3cd0d08798db597cb306e134596f2acd3ff03bd2624cded8594de4bfb5bf"
metafile = true

[[files]]
file = "mods/cloak-of-gray-tomorrow.pw.toml"
hash = "2451ed4f627324bfed1d5c2c38a3fc8e0810d8dfb3e679700a5fd2db1f7eb998"
metafile = true

[[files]]
file = "mods/colossalcakes.pw.toml"
hash = "d0d250eaac58a71e6bb08bdfca0ce52e97ad9dde504e7f5d892bc0d84e7916ed"
metafile = true

[[files]]
file = "mods/command-actions.pw.toml"
hash = "0f4065ebf6cdc217a2858b3e5d2558d921d4f9c819375a8169b26fa88dbdf6a4"
metafile = true

[[files]]
file = "mods/crafting-bench.pw.toml"
hash = "8fcbea58b6efc9e798f32b652a492f361ac05ffdcd92dc4ef368acf54afa6f1c"
metafile = true

[[files]]
file = "mods/drogtor.pw.toml"
hash = "0da6c09f627126988afb5a192e95147bf0911f954f07cf756550704c9ab4f540"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "4de24ddd51cba8dfddd2e66fa2c659013596289839f888a0c8f6222669e75637"
metafile = true

[[files]]
file = "mods/echoes-of-the-past.pw.toml"
hash = "63f6012c29b61b785795ee45c75d3701a592c48529b051a7f85dc966a6efcb24"
metafile = true

[[files]]
file = "mods/emerald-expansions.pw.toml"
hash = "237e340ea10313e013642a7c24f68f1a14bec499cace53b6bdc91794228a4256"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "7250c341106f7097064eaf65f72cb3d7668f0c3a28a67278442f42441020d465"
metafile = true

[[files]]
file = "mods/energized-redstone.pw.toml"
hash = "30d041c89fe8811e32fee5dbe1bcba2e4482d05056864bcf79984a6bc3559e58"
metafile = true

[[files]]
file = "mods/engination.pw.toml"
hash = "8dc5e3aee87a1e2389fed43af22b8723f79a8acfa42cead83d12a4c9c8bb9269"
metafile = true

[[files]]
file = "mods/ethicalmeatfields.pw.toml"
hash = "e784483f27b62bec6e98f86a613236c53cd9de99fcf8cc85c661816f73f7cc47"
metafile = true

[[files]]
file = "mods/fabrication.pw.toml"
hash = "c4c771449e4fec227ee6d0477c2d32dbdcd8a0e3f9675140e53222363eda7112"
metafile = true

[[files]]
file = "mods/fabrictailor.pw.toml"
hash = "b3e1f7b080b5c4a2e3de434a6873d84ba5bd357dff99268d45db4a79fb6d43b9"
metafile = true

[[files]]
file = "mods/fox-plushies.pw.toml"
hash = "2506864b4b09b94a6cdd7162512af422a12d031cf7eb6a090a8be6a0be6fb0f7"
metafile = true

[[files]]
file = "mods/glowcase.pw.toml"
hash = "c0155534d82a27cc7846918edf1b708f215e0964ad43cf49704743b62ff9dd00"
metafile = true

[[files]]
file = "mods/goldtelepads.pw.toml"
hash = "29bda491e45162f25c49bde3160e63958f01085e433fe81c49bb2128ff3a87cb"
metafile = true

[[files]]
file = "mods/heighthaltingheels.pw.toml"
hash = "a4d5e5090908a5abcce2c4f407f341e6b22873d7227ed26b986466a3bacfbbfc"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "e8168531c092676d47cac3657bfc525f096f11ff5372ce6e322ad57778b81635"
metafile = true

[[files]]
file = "mods/infused-immortality.pw.toml"
hash = "a27cff617de7bb6d08f5fe2a694d3e4aedfb1bf2f39209749ba19941a2ed900e"
metafile = true

[[files]]
file = "mods/ingstorm.pw.toml"
hash = "a12d26e421b1fd0dc0ec523b206b47a523c6b9b6ccc19420c83ece2af0ddcfcf"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "d4dd336cc77340a6429082e8a6f848c9db459a77e4d5703c02beea8b2a016015"
metafile = true

[[files]]
file = "mods/its-poppin.pw.toml"
hash = "52cf52e31f2097d9588a42a51f83719ca339433c05f889429e6b24fd1bf8a78f"
metafile = true

[[files]]
file = "mods/jackogolem.pw.toml"
hash = "d068d449d658439eff43fff372fac5392228cf6a0540dd0a94de0e0efb089f20"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "21c5ff2c70f953eaddf10d3ef09538d99da19c4cfe32aa251ef162b4d78c8160"
metafile = true

[[files]]
file = "mods/jar-it.pw.toml"
hash = "ee413b3ea2c3f2ed3adda268dfe32473fac7d245690f8d0e135bcaddaf4025f6"
metafile = true

[[files]]
file = "mods/kahur.pw.toml"
hash = "ff6e0b1c5d972ff070ad0ac7023649b814052775db486917917e0eaa298a4c64"
metafile = true

[[files]]
file = "mods/kettle.pw.toml"
hash = "94865ef86f229df1ce78a22498f41779fd56313c6e7c8efe678f7253c56c09db"
metafile = true

[[files]]
file = "mods/kofi-table.pw.toml"
hash = "8726c3ef33756d400f3f5fc00da96608ced3a11742682ef29bd4287225fe70d8"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "998f45a9037fa4663bc5e2bea5de925bf4ce6352328fcaaa830db8466cc62416"
metafile = true

[[files]]
file = "mods/la-cucaracha.pw.toml"
hash = "e24c81418be785a19f6903c76598989fcb36e3f6406af4a911bfd8f43a2cc6b7"
metafile = true

[[files]]
file = "mods/lanyard.pw.toml"
hash = "bb7151b7e10df8cec028ccf61871b86e09304deb1754e905d0149b32f33ed10a"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "mods/limits-grapple.pw.toml"
hash = "d3e7af0e25bda336bf9991e8a4372b75212dab4fc74eaaebb33f04a5347ac17f"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "7cc268ba8c316a732881e631e00db7cf8db0891f24155475db0a4e88840cdfe8"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "c038a6ea641541af0aee754c41df71ccb662245863cecb43d64c202baf561291"
metafile = true

[[files]]
file = "mods/luckyducks.pw.toml"
hash = "58ab921c1b4498f5fb5d73a8420eeae621095da045c00e6f51c2a75ca581c0ff"
metafile = true

[[files]]
file = "mods/maprender.pw.toml"
hash = "780cbd198709c4253581abdf64223ef8c3ceeb6a176b596ea18e7480364cf396"
metafile = true

[[files]]
file = "mods/meowing.pw.toml"
hash = "9418168578c73fef540382b2e3c111ec0099531d00e245dbe0db7cbbb3b119ed"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "1c68b1e077a77dfa2cd5a63b9ad73b11406e4c0bb13ef72a4c337cb50f188740"
metafile = true

[[files]]
file = "mods/mineball.pw.toml"
hash = "9d73314bcbc185f89b86ef03e09b07fbbecfd30781b9407dad57d4cf454d3144"
metafile = true

[[files]]
file = "mods/minecalc.pw.toml"
hash = "6cb5fea02043f49dead87f9a8e9709f7c725df5fcd418d5f682c9c84d67dd253"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "24b56cdea0d96fc1b03b8cb6e6bb4b600c6fe730f7cd86e84004d100779ad5a1"
metafile = true

[[files]]
file = "mods/mods-in-a-jar.pw.toml"
hash = "08436eff9f291c980c528141b3d2d2ff99397938db5b5b42968d353180405bca"
metafile = true

[[files]]
file = "mods/modulus.pw.toml"
hash = "f82e7722898bd7dce6a3f84cf555713afdb3a38bff1dc8883f2a5d113d868114"
metafile = true

[[files]]
file = "mods/moovy.pw.toml"
hash = "77fa9e9e750ce2c064b9abae71fdcd76a936fc4fac41e9f2a62c5170db5ca7d4"
metafile = true

[[files]]
file = "mods/mushroom-mod.pw.toml"
hash = "0ef254d9d44942f33ee3405ce0e253dd883b922e5af32943dc2656fa964d4f70"
metafile = true

[[files]]
file = "mods/myriad-bows.pw.toml"
hash = "229d553cd29685e4a271f3528626eead01490216427cda759212da45ac024ec0"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "86fd76830339379e145c23747d51608f1a3165df7e747184f2d9fc890c7ab385"
metafile = true

[[files]]
file = "mods/packy.pw.toml"
hash = "fc1b82fc641cc035d9528146b1301f34ae43b8e914a639e93749ccd4f6aeb017"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "d2dbe33fa927b10398c5a1a42ca8a2f925a802b7a0bef4d1e76ab5ff54a25aba"
metafile = true

[[files]]
file = "mods/patterns.pw.toml"
hash = "2c81c40f2ce7dc8b1fa39fc67dadec4e8a75e1a8ebb41fa4dfc588ffe06c369c"
metafile = true

[[files]]
file = "mods/peculiar-pieces.pw.toml"
hash = "e3aa6a74faad8600b7564850a071e5fa96fcef934ea87ee020390d59eba137b3"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
hash = "b8fc16dda19cf918380c01d8ffb49c1380904dbe6d8290c6758e4ae5e07b1a06"
metafile = true

[[files]]
file = "mods/picturesign.pw.toml"
hash = "de98473ec784d53d4dc03aeb17dbc562658d02da5ff9222b43b9b87c20b51dd9"
metafile = true

[[files]]
file = "mods/polaroid.pw.toml"
hash = "c531b07068714e4221b32a301712cc034856b9628ae214511125ab5088e7492f"
metafile = true

[[files]]
file = "mods/pressalttomeow.pw.toml"
hash = "d85441641625c3c7634aeb801297eaba457314ef951d8bf222f4966a51b01109"
metafile = true

[[files]]
file = "mods/pridestrips.pw.toml"
hash = "009459384f38af33e1b7bd341e6e77166f45cc5140719581a76fc3ecc89569ec"
metafile = true

[[files]]
file = "mods/qkl.pw.toml"
hash = "c9b5c7f923336eb60458492ee72e30471edefa0b5b897d279def756101895737"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "942915b4c02216c49d7ed821b2d062f5a96f921f3dde628952b6401aa38c98a4"
metafile = true

[[files]]
file = "mods/quiltgoslighlyfasterlol.pw.toml"
hash = "feee9284053ffd6435907d1bf3b5fdb7e9010237bb2a4b6a912d6f1389f8def7"
metafile = true

[[files]]
file = "mods/recovery-plus.pw.toml"
hash = "90d6e7adaf265d6b90fb5eef0138b18befb4d00d41344d5a6046148cc37c66fb"
metafile = true

[[files]]
file = "mods/redderstone.pw.toml"
hash = "3c0cf0c7d636df22f7672382fed2ffa8b7c80438928b13f53a1d0c80f8d6353c"
metafile = true

[[files]]
file = "mods/relativity.pw.toml"
hash = "bb8bb0ad7a7bca396510ca41e08df4bcaeed4fb8393bf1662cff198026af3a75"
metafile = true

[[files]]
file = "mods/restful-hellscape.pw.toml"
hash = "81af4a423b2b51c5bf7f5a31712653827b1854fa98cf9f846b18ea882fe1d5c8"
metafile = true

[[files]]
file = "mods/runic-railguns.pw.toml"
hash = "6447b49ba96a71f6982e4ca30b0baec38d9c7be3313a3c3533bfbd47fa54f1fe"
metafile = true

[[files]]
file = "mods/scarves.pw.toml"
hash = "1669901fdb99a9626180855901c1534b54a3475efd6b07a691a390b77580d631"
metafile = true

[[files]]
file = "mods/sharp-tone.pw.toml"
hash = "72112c2295123556b5a9b8d1ce20a06455b6fcaa82f443de6ba6285ad2f86e8a"
metafile = true

[[files]]
file = "mods/simplexp.pw.toml"
hash = "13bed28c4e374dcc8991a95197a09a52e433f45d2734bf74bc452cdeee7d4488"
metafile = true

[[files]]
file = "mods/smunnel.pw.toml"
hash = "296dce779c2bec13d027d6bafca957acb7ada85ed58967bb49e8c99fa43b7492"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "aa4dcf55ac3191b0b31437521714c1d28364c3396cf06ef07fa76a08488c1837"
metafile = true

[[files]]
file = "mods/soul-under-sculk.pw.toml"
hash = "6d07907030132a2c05f1757da0937bf34b3dc98d64176046219d837627c19f7e"
metafile = true

[[files]]
file = "mods/soul-vitric.pw.toml"
hash = "dcdb60c59e8619fd4cae9b91a62b4e0bc920c33e7512a76a680720fbaed1757d"
metafile = true

[[files]]
file = "mods/souper.pw.toml"
hash = "e97be39323a8308156c6104794303076f97b5e09c124ce423896355cdd8fa247"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "e63228fdadc03ceaac771202e588fbf174bc0d47d5f20de863a5b8a5d233058a"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "be68ef606c339bbb22f2b812db1e5264d9e3335befc0c348d4dc91a8a3e72e17"
metafile = true

[[files]]
file = "mods/succ.pw.toml"
hash = "74183ab677fd0c5275725dd22859f26c952c2369bbe4c0eedb5a38df6a5e8fa7"
metafile = true

[[files]]
file = "mods/switchy-inventories.pw.toml"
hash = "4beb078cf0a07b08eed69ae2f698830c208833fa4887323279e81b2111c91388"
metafile = true

[[files]]
file = "mods/switchy.pw.toml"
hash = "692cb8912b45d8d62a296ff22db90ece8b9e5ebbd6c44b58080e99d489be58d7"
metafile = true

[[files]]
file = "mods/taterzens.pw.toml"
hash = "853f3e9b78f68e18118cdd92ff3619d2f849cefae363bb97808a45d3de896970"
metafile = true

[[files]]
file = "mods/the-printer.pw.toml"
hash = "a91cf089cc33f289f4737ce72eedd34471787ab4686cbd8a1f1848ae48b7bb7a"
metafile = true

[[files]]
file = "mods/thematchmakers.pw.toml"
hash = "cfe754b658854e10d73f0b63d07aba17418134858d8d163a4c156ad27450d31b"
metafile = true

[[files]]
file = "mods/tree-hat.pw.toml"
hash = "ae2ce11325bd06ac85519db134001b25d35b5ad1ae6bf42051b3a4ce2a78ae11"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "842711b0a1baa2fc6bd2ef6c1953c735f68e73c6b7a13dee723851feb183349c"
metafile = true

[[files]]
file = "mods/tropics.pw.toml"
hash = "bd6eeee400e2acef35b53129f15b616cdcf008c028c3485be313a716014d34d0"
metafile = true

[[files]]
file = "mods/untill.pw.toml"
hash = "6e0a0709ad8c8dbe15069439ac6c72698fd3a7e0327cb2dd0846076f808d9881"
metafile = true

[[files]]
file = "mods/vanity-splash-text.pw.toml"
hash = "97b237efdd455619095586dddbf65aa84b964db7781a4f40798f6042b3ad17d5"
metafile = true

[[files]]
file = "mods/villagerbefriending.pw.toml"
hash = "3927b6f269aca5a3cfb72b38119e5c03a4760840afcae560f9c37f2cf506b125"
metafile = true

[[files]]
file = "mods/visible-barriers.pw.toml"
hash = "b5e708bc1681f12638a7c82d234e4292749cc05ef5ea09a226f9e5086e2e71ea"
metafile = true

[[files]]
file = "mods/wenospeakumbrellarino.pw.toml"
hash = "7bb0072c0c67e2866a21ec175d5e536324a5b5ff94ac0c5f5e771c032365a5cf"
metafile = true

[[files]]
file = "mods/whipdashing.pw.toml"
hash = "c774b5349d333117a289e9f59e850247c276712783c4ec110ed1a72239e68f6e"
metafile = true

[[files]]
file = "mods/worldinajar.pw.toml"
hash = "38054df2a6e448f7c5f9c81934352e201a5fa434d04f6962982d10925cd4ab7d"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
hash = "de08ce31ccfbd64fb308ddb0d1076d4e6cd65ac43bd6a16e57e01a1d14336428"
metafile = true

[[files]]
file = "mods/yardwork.pw.toml"
hash = "cfae75716e1d9a4e459fe088530ea48eadddd9d1728bd2c375c9f24a9cf4244f"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "7c2712882baa2ed177b9b961cc1052b857f11ed1455609f9e9f01332c0317f12"
metafile = true

[[files]]
file = "mods/yttr.pw.toml"
hash = "a7a46a90f6e06ddc18474a65ad015ed7591b69144f7d2458ba4da344448d4c2c"
metafile = true
